# Use https://marketplace.visualstudio.com/items?itemName=humao.rest-client to execute these in VSCode

### Message data
GET http://localhost:14265/api/v1/messages/02206accbebd246137b8be23c700c9278277ea4118ec5be0c94361673ee45e95
Content-Type: application/json
