# Use https://marketplace.visualstudio.com/items?itemName=humao.rest-client to execute these in VSCode

### Address data
GET http://localhost:14265/api/v1/addresses/091dc94a7f12f3913dce4dc4f7fc9813461d8e296a011d979fe98c95d854483c
Content-Type: application/json
